unknown:
	@echo Makefile supports the following targets 
	@echo "    clean-build"
	@echo "    clean-run"
	@echo "    veryclean"

veryclean: clean-build clean-run

clean-build:
	/bin/rm -rf AMGMk-* *.o

clean-run:
	/bin/rm -rf hpctoolkit-* AMGMk-*.hpcstruct 


